### PR TITLE
[WIP] PNG trials

### PR DESCRIPTION
**Pull request by rgbkrk**
Trying out creating a PNG using a PNG library. Not performant, pretty bad honestly. It's late though so I'll just post this and take a crack at it later.

### CODE REVIEW

**Comment by kitten** [comment]
@rgbkrk Last time I tried node-png, it wouldn't compile. Are you sure it does compile on recent versions of node? E.g. v3, v4, v5?

**Comment by rgbkrk** [comment]
I'm on v5.

**Comment by rgbkrk** [comment]
I'm using [`node-png`](https://www.npmjs.com/package/node-png) not [`png`](https://www.npmjs.com/package/png). It has no native dependencies.

**Comment by rgbkrk** [comment]
Closing in favor of the current player model, setting pixels directly.

**Pull request closed without merging**
