### PR TITLE
Go big or go home, canvas edition.

### PR DESCRIPTION
**Pull request by rgbkrk**
We can render wayyyyyy more players when using canvas. Only trouble is that trying to provide tool tips on hovering would require some major data changes.

Anyways, here's a map with 25083 "players" on it:

image

### CODE REVIEW

**Comment by rgbkrk** [comment]
image

**Comment by kitten** [comment]
@rgbkrk :tada: Depending on how many coordinate cells you need you can create a hashmap using array and Immutable.js lists. You'd need 2048x2048 cells = 4194304. O(log32 N) is totally feasible even for such a high number. If that doesn't work we could still replace the map with a list.

I suggest the Cantor pairing function -- or anything else. This just came to mind

Something like this: https://gist.github.com/philplckthun/819db9185dcab2ae60fd

Haven't tested this yet ;)

**Comment by rgbkrk** [comment]
Yeah and since we'd have a full array format, it might as well be the image data to provide the canvas.

That then comes down to `2048 * 2048 * 3 bytes ~= 12.6 MB`. Not that we'll have 4.1 million players by any means. :wink:

**Comment by rgbkrk** [comment]
The Cantor pairing function will definitely work well there!

The only issue I see is that updating the player's position isn't removing their previous position.

**Comment by kitten** [comment]
@rgbkrk It is removing their previous position ...

**Comment by rgbkrk** [comment]
Derp. I see it now.

**Comment by rgbkrk** [comment]
```
this.playerCoors[pos] = this.playerCoors[pos].filter(x => x !== id);
```

**Pull request merged**
